FROM python:3.11-slim

WORKDIR /app

# Copia dependências
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copia o conteúdo da pasta app
COPY app ./app

EXPOSE 8000

# Executa o FastAPI dentro da pasta /app/app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]